@echo off
chcp 65001 > nul

REM =================================================================
REM Begin Write of FitNesseRoot\Vars.wiki
REM -----------------------------------------------------------------
for %%I in ("%~dp0..") do (
    set "PROJECT_ROOT=%%~fI"
)
echo # Do not edit this file! It is generated by RunFitnesse.bat> FitNesseRoot\Vars.wiki
echo !define PROJECT_ROOT {%PROJECT_ROOT%}>> FitNesseRoot\Vars.wiki   
echo !define FITNESSE_ROOT {%~dp0FitNesseRoot}>> FitNesseRoot\Vars.wiki
if exist %PROJECT_ROOT%\..\WDDelphiTools (
  for %%I in ("%PROJECT_ROOT%\..\WDDelphiTools") do (
      echo !define WDDT_ROOT {%%~fI}>> FitNesseRoot\Vars.wiki
  )
)
if exist %PROJECT_ROOT%\..\WinDomina (
  for %%I in ("%PROJECT_ROOT%\..\WinDomina") do (
      echo !define WINDOMINA_ROOT {%%~fI}>> FitNesseRoot\Vars.wiki
  )
)
REM -----------------------------------------------------------------
REM End Write of FitNesseRoot\Vars.wiki
REM =================================================================

set "JAVA_OPTS="
if "%~1"=="-debug" (
    set "JAVA_OPTS=-Dslim.port=9000 -Dslim.pool.size=1 "
)

java %JAVA_OPTS%-jar fitnesse-standalone.jar
