@echo off
chcp 65001 > nul

for %%I in ("%~dp0..") do set "PROJECT_ROOT=%%~fI"

echo # Do not edit this file! It is generated by RunFitnesse.bat> FitNesseRoot\Vars.wiki
echo !define PROJECT_ROOT {%PROJECT_ROOT%}>> FitNesseRoot\Vars.wiki   
echo !define FITNESSE_ROOT {%~dp0FitNesseRoot}>> FitNesseRoot\Vars.wiki

set "JAVA_OPTS="
if "%~1"=="-debug" (
    set "JAVA_OPTS=-Dslim.port=9000 -Dslim.pool.size=1 "
)

java %JAVA_OPTS%-jar fitnesse-standalone.jar
